### PR TITLE
add Date support

### PR DESCRIPTION
**Pull request by minedeljkovic**
This adds Date type support

### CODE REVIEW

**Comment by gcanti** [comment]
Hi @minedeljkovic,

AFAIK `Date`s already work:

```js
function foo(d: Date) {}

foo(1) // throws [tcomb] Invalid value 1 supplied to d (expected a Date)
```

Did you find some issues?

**Comment by minedeljkovic** [comment]
Interesting, cause I first created tests and they failed.

Anyway, here is my motivating example from app I am working on:

Flow:
```js
type DelatnostPreview = {
  id: number,
  version: number,
  kreiraoVreme: Date,
};
```

Before adding Date support:
```js
var DelatnostPreview = _tcomb3.default.interface({
  id: _tcomb3.default.Number,
  version: _tcomb3.default.Number,
  kreiraoVreme: Date,
}, 'DelatnostPreview');
```

After adding Date support:
```js
var DelatnostPreview = _tcomb3.default.interface({
  id: _tcomb3.default.Number,
  version: _tcomb3.default.Number,
  kreiraoVreme: _tcomb3.default.Date,
}, 'DelatnostPreview');
```

**Comment by gcanti** [comment]
Every irreducible type defined using `instanceof` (e.g. `Date`, `Error`, etc...) should work by default, no need for additional support (see https://github.com/gcanti/tcomb/blob/master/lib/is.js#L8)

**Comment by minedeljkovic** [comment]
I see, but I also need this for runtime introspection, not only type checking.

**Comment by gcanti** [comment]
Not sure why you *need* `t.Date` for runtime type introspection. Now you'd get `Date` instead of `t.Date`, what's you use case? Could you explain why this is a problem? (`t.Date`, `t.Error`, `t.RegExp` may be considered legacy after generic class support has been added). 

Example: there is no `t.Promise` but you can get type checking and runtime type introspection nevertheless

```js
function foo(p: Promise) {}

foo(1) // throws [tcomb] Invalid value 1 supplied to p (expected a Promise)

type MyType = {
  p: Promise
};

type MyType = {
  p: Promise
};

const ReifiedMyType = (({}: any): $Reify<MyType>)
console.log(ReifiedMyType.meta.props.p) // => Promise
console.log(t.is(1, ReifiedMyType.meta.props.p)) // => false
console.log(t.is(Promise.resolve(1), ReifiedMyType.meta.props.p)) // => true
```

**Comment by minedeljkovic** [comment]
My use case is Date deserialization using fromJSON. I think this is extremely common use case, which you also used as an example [here](https://github.com/gcanti/tcomb/blob/master/docs/API.md#the-libfromjson-module). The type is also reified flow type.

Now, I see 2 options to go without t.Date support:
1. Add fromJSON static method to Date constructor (I think this is bad practice)
2. Write my own fromJSON runtime introspection that handles Date as a special case

**Comment by gcanti** [comment]
Well, now I understand, the problem is `fromJSON`. 

Another option would be to fix `fromJSON`, which currently doesn't handle constructors https://github.com/gcanti/tcomb/pull/230.

Then you will have 2 choices:

- define your own static function (`Date.fromJSON`)
- leverage the default behavior (`new Date(<your-serialization-format>)`)

**Comment by minedeljkovic** [comment]
> leverage the default behavior (`new Date(<your-serialization-format>`))

I am ok with this option  👍

**Comment by gcanti** [comment]
Ok, closing this. I'll release that fix asap

**Pull request closed without merging**
