### PR TITLE
BREAKING CHANGE: Upgraded to support babel v6.

### PR DESCRIPTION
**Pull request by ctrlplusb**
- .babelrc added to project.
  - Peer dependencies for 'babel' and 'babel-plugin-syntax-flow' packages have
    been added.
  - Plugin updated accordingly to match the required format of babel v6.

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Solves issue #7 
Supersedes PR #8 - Thanks @mlegenhausen for the inspiration! x 

All tests passing, would appreciate someone having a scan.

@gcanti @mlegenhausen

**Comment by gcanti** [comment]
@ctrlplusb this is awesome! Thanks a lot. Going to merge

**Comment by ctrlplusb** [comment]
No problem!  Thank you for the quick merge and for your amazing work on tcomb.

I went full circle through so many type systems (including flow and typescript) and honestly believe tcomb is the best candidate.  I'm babel 6 guy, so had to make this happen! :)

**Comment by mlegenhausen** [comment]
Thanks for helping me out :)

**Pull request merged**
