### PR TITLE
Babel 6 support added

### PR DESCRIPTION
**Pull request by mlegenhausen**
As wished in #7. First steps for a port to babel 6.

Not all unit tests are currently working. This transformation only works for the first function in the `NodePath`. Currently I get a recusion from `babel-traverse` when replacing the current node. See my TODO in `src/index.js`. Help is welcome.

Also is the manually added of `syntax-flow` needed to get the plugin working.

Please review, give feedback, any help welcome :)

### CODE REVIEW

**Comment by volkanunsal** [comment]
+1

Very interested in seeing this merged.

**Comment by jewelsjacobs** [comment]
+1 pls merge :)

**Comment by gcanti** [comment]
@jewelsjacobs AFAIK this is a, not yet functional, work in progress. @mlegenhausen could you confirm?

**Comment by mlegenhausen** [comment]
Yes I would need someone to with more experience with babel to review my changes and help me with the last recursion issue. Currently I haven't the time to work further on the needed changes, so anyone who can take over is welcome.

**Comment by hsunami** [comment]
+1...super useful

**Comment by hsunami** [comment]
@gcanti will you check and approve this PR anytime soon? choosing between other typed solutions and tcomb at the moment, and this is definitely a contributing factor. thanks in advance

**Comment by gcanti** [comment]
@hsunami I still use babel 5, I don't plan to work on this before switching to 6, however reviews and/or PRs are very welcome

**Comment by hsunami** [comment]
@gcanti thanks for the quick reply

**Comment by ctrlplusb** [comment]
I'm also in the position where I don't know enough about babel plugin development to be of use for this issue.

However, there is an amazing guide available on how to develop babel plugins:
https://github.com/thejameskyle/babel-handbook

If I can miracle out some spare time to skill up on this I hope to help, but thought that it's worth linking the above in this thread in the interim.

**Comment by ctrlplusb** [comment]
Hi @mlegenhausen 

Thanks for starting this!  I have a tiny bit of time available so I am trying to help out with this.  I've been reading the babel-handbook I linked above and rebuilding the plugin from the ground up at the moment.  Sorry for going against your PR with my own, but I think the only way I can produce something of value is to start from nothing up.  Obviously referencing your PR and the existing source is hugely helpful.  

To be honest I am not even sure I am up to the technical challenge, but thus far I seem to have dodged the infinite loop scenario you highlighted in your codebase.  If I make any more progress I'll commit and expose.  Hope to get your input and the input of anyone else who is interested.

Thanks

**Comment by justingreenberg** [comment]
@ctrlplusb 👍 be sure to check out https://astexplorer.net/ it's an amazing tool

**Comment by ctrlplusb** [comment]
Good news everyone!

https://www.dropbox.com/s/45ue7i9717l9uv2/Screenshot%202016-04-23%2020.28.42.png?dl=0

**Comment by ctrlplusb** [comment]
@gcanti @mlegenhausen 
What's the best step forward for me here? Try and merge my code into this pull request or create a new one?

**Comment by gcanti** [comment]
> create a new one

👍

**Comment by gcanti** [comment]
Closing in favour of https://github.com/gcanti/babel-plugin-tcomb/pull/12

**Pull request closed without merging**
