### PR TITLE
Added travis support for modern node versions

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by gcanti** [comment]
Hi @amilajack, 
what's "appveyor"? and why "0.12" has been removed?

**Comment by amilajack** [comment]
My bad. Fixed the title. Appveyor is a ci service for windows.

**Comment by amilajack** [comment]
Fixed

**Comment by gcanti** [comment]
Ah ok, thanks. Could you please squash the commits? Going to merge

**Pull request closed without merging**
